### ISSUE TITLE
How do I compile svt-av1-psy with libdovi and libhdr10plus on msvc?

### ISSUE THREAD

**Issue by Uranite** [Patman86/SVT-AV1-Mod-by-Patman#7]
Hi, I'm just wondering, how do I compile svt-av1-psy with libdovi and libhdr10plus on msvc?
I already know how to compile with msvc, just not with libdovi and libhdr10plus support, It'll be great to know how

**Comment by Patman86** [comment]
I will describe this to you in more detail in the next few days. I also had to try out a lot 🫣

**Comment by Patman86** [comment]
So, here are my instructions on how to compile the SVT-AV1-PSY with libdovi and libhdr10plus.

First you have to download the installation file for Rust under Windows: [Rust-MSVC](https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe)

After installing Rust you have to enter the following command in the command line: `cargo install cargo-c`, because libdovi and libhdr10plus are written in rust-c.

To compile the libraries you have to clone the repositories or download them as a zip file. Once you have unpacked the repositories on your desired drive you have to go to the dolby_vision folder to compile libdovi. Open the command window in this folder and enter the following command: `cargo cinstall --release --prefix=drive:\to\SVT-AV1-PSY\Source\dovi`. All the required files will then be written to this folder.

It is similar for libhdr10plus, go to the main folder of hdr10plus and open the command window again and enter the command to compile `cargo cinstall --release --prefix=drive:\to\SVT-AV1-PSY\Source\hdr10plus`.

So you already have the libraries you need to build the file.

Now you have to adjust two files in the source folder of SVT-AV1-PSY, otherwise it won't work. Firstly, the file `Source/App/EncApp/CMakeLists.txt` and the file `Source/App/EncApp/EbAppConfig.h`. You can see the changes that need to be made in my commits in my Git. Absolute paths must be stored.

You can try it out and see if you can handle it. If you have any further questions, just let me know 😉

**Comment by Uranite** [comment]
All good 👍

**Comment by Uranite** [comment]
Actually I forgot to mention, the correct path for dovi is `Source\dovi\msvc` and for hdr10plus is `Source\hdr\msvc`

**Comment by Patman86** [comment]
Only in my case, because I create the libs for gnu and msvc and use the same script. Otherwise that wouldn't be necessary 😉

**Comment by Uranite** [comment]
I just don't really feel like modifying the code 😄

**Comment by Patman86** [comment]
😂🤣
